#
# my-app.yaml
#

modules:
  bucket:
    source: aws/5/s3-bucket
    vars:
      default_tags: ${vars.default_tags}    # from infra/vars.yaml

  lock_table:
    source: aws/5/dynamodb
    vars:
      dynamodb_hash_key: LockID
      default_tags:      ${vars.default_tags}

  app_user:
    source: aws/5/iam-user
    vars:
      iam_user_create_access_key: false
      default_tags:               ${vars.default_tags}

  app_user_policy:
    source: aws/5/iam-policy
    vars:
      iam_policy_user_name: ${module.app_user.user_name}
      iam_policy_statements:
        - effect: Allow
          actions: [s3:GetObject, s3:PutObject, s3:DeleteObject, s3:ListBucket]
          resources:
            - ${module.bucket.bucket_arn}
            - ${module.bucket.bucket_arn}/*
        - effect: Allow
          actions: [dynamodb:PutItem, dynamodb:GetItem, dynamodb:DeleteItem, dynamodb:DescribeTable]
          resources:
            - ${module.lock_table.table_arn}

  cicd_user:
    source: aws/5/iam-user
    vars:
      iam_user_create_access_key: true
      secrets_manager_name:       "myapp/cicd-user"
      default_tags:               ${vars.default_tags}

  cicd_user_policy:
    source: aws/5/iam-policy
    vars:
      iam_policy_user_name: ${module.cicd_user.user_name}
      iam_policy_statements:
        - effect: Allow
          actions: [s3:PutObject, s3:DeleteObject, s3:ListBucket]
          resources:
            - ${module.bucket.bucket_arn}
            - ${module.bucket.bucket_arn}/*
